# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/altar/Desktop/Projects/Cell Library"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/altar/Desktop/Projects/Cell Library"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/altar/Desktop/Projects/Cell Library/CMakeFiles" "/home/altar/Desktop/Projects/Cell Library/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/altar/Desktop/Projects/Cell Library/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cells.elf

# Build rule for target.
cells.elf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cells.elf
.PHONY : cells.elf

# fast build rule for target.
cells.elf/fast:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/build
.PHONY : cells.elf/fast

graphics/src/c2Functions.o: graphics/src/c2Functions.cpp.o

.PHONY : graphics/src/c2Functions.o

# target to build an object file
graphics/src/c2Functions.cpp.o:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/c2Functions.cpp.o
.PHONY : graphics/src/c2Functions.cpp.o

graphics/src/c2Functions.i: graphics/src/c2Functions.cpp.i

.PHONY : graphics/src/c2Functions.i

# target to preprocess a source file
graphics/src/c2Functions.cpp.i:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/c2Functions.cpp.i
.PHONY : graphics/src/c2Functions.cpp.i

graphics/src/c2Functions.s: graphics/src/c2Functions.cpp.s

.PHONY : graphics/src/c2Functions.s

# target to generate assembly for a file
graphics/src/c2Functions.cpp.s:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/c2Functions.cpp.s
.PHONY : graphics/src/c2Functions.cpp.s

graphics/src/c2Graphics.o: graphics/src/c2Graphics.cpp.o

.PHONY : graphics/src/c2Graphics.o

# target to build an object file
graphics/src/c2Graphics.cpp.o:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/c2Graphics.cpp.o
.PHONY : graphics/src/c2Graphics.cpp.o

graphics/src/c2Graphics.i: graphics/src/c2Graphics.cpp.i

.PHONY : graphics/src/c2Graphics.i

# target to preprocess a source file
graphics/src/c2Graphics.cpp.i:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/c2Graphics.cpp.i
.PHONY : graphics/src/c2Graphics.cpp.i

graphics/src/c2Graphics.s: graphics/src/c2Graphics.cpp.s

.PHONY : graphics/src/c2Graphics.s

# target to generate assembly for a file
graphics/src/c2Graphics.cpp.s:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/c2Graphics.cpp.s
.PHONY : graphics/src/c2Graphics.cpp.s

graphics/src/c2Shader.o: graphics/src/c2Shader.cpp.o

.PHONY : graphics/src/c2Shader.o

# target to build an object file
graphics/src/c2Shader.cpp.o:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/c2Shader.cpp.o
.PHONY : graphics/src/c2Shader.cpp.o

graphics/src/c2Shader.i: graphics/src/c2Shader.cpp.i

.PHONY : graphics/src/c2Shader.i

# target to preprocess a source file
graphics/src/c2Shader.cpp.i:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/c2Shader.cpp.i
.PHONY : graphics/src/c2Shader.cpp.i

graphics/src/c2Shader.s: graphics/src/c2Shader.cpp.s

.PHONY : graphics/src/c2Shader.s

# target to generate assembly for a file
graphics/src/c2Shader.cpp.s:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/c2Shader.cpp.s
.PHONY : graphics/src/c2Shader.cpp.s

graphics/src/example.o: graphics/src/example.cpp.o

.PHONY : graphics/src/example.o

# target to build an object file
graphics/src/example.cpp.o:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/example.cpp.o
.PHONY : graphics/src/example.cpp.o

graphics/src/example.i: graphics/src/example.cpp.i

.PHONY : graphics/src/example.i

# target to preprocess a source file
graphics/src/example.cpp.i:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/example.cpp.i
.PHONY : graphics/src/example.cpp.i

graphics/src/example.s: graphics/src/example.cpp.s

.PHONY : graphics/src/example.s

# target to generate assembly for a file
graphics/src/example.cpp.s:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/example.cpp.s
.PHONY : graphics/src/example.cpp.s

graphics/src/glad.o: graphics/src/glad.c.o

.PHONY : graphics/src/glad.o

# target to build an object file
graphics/src/glad.c.o:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/glad.c.o
.PHONY : graphics/src/glad.c.o

graphics/src/glad.i: graphics/src/glad.c.i

.PHONY : graphics/src/glad.i

# target to preprocess a source file
graphics/src/glad.c.i:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/glad.c.i
.PHONY : graphics/src/glad.c.i

graphics/src/glad.s: graphics/src/glad.c.s

.PHONY : graphics/src/glad.s

# target to generate assembly for a file
graphics/src/glad.c.s:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/glad.c.s
.PHONY : graphics/src/glad.c.s

graphics/src/gui/c2GUI.o: graphics/src/gui/c2GUI.cpp.o

.PHONY : graphics/src/gui/c2GUI.o

# target to build an object file
graphics/src/gui/c2GUI.cpp.o:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/gui/c2GUI.cpp.o
.PHONY : graphics/src/gui/c2GUI.cpp.o

graphics/src/gui/c2GUI.i: graphics/src/gui/c2GUI.cpp.i

.PHONY : graphics/src/gui/c2GUI.i

# target to preprocess a source file
graphics/src/gui/c2GUI.cpp.i:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/gui/c2GUI.cpp.i
.PHONY : graphics/src/gui/c2GUI.cpp.i

graphics/src/gui/c2GUI.s: graphics/src/gui/c2GUI.cpp.s

.PHONY : graphics/src/gui/c2GUI.s

# target to generate assembly for a file
graphics/src/gui/c2GUI.cpp.s:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/gui/c2GUI.cpp.s
.PHONY : graphics/src/gui/c2GUI.cpp.s

graphics/src/gui/c2Text.o: graphics/src/gui/c2Text.cpp.o

.PHONY : graphics/src/gui/c2Text.o

# target to build an object file
graphics/src/gui/c2Text.cpp.o:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/gui/c2Text.cpp.o
.PHONY : graphics/src/gui/c2Text.cpp.o

graphics/src/gui/c2Text.i: graphics/src/gui/c2Text.cpp.i

.PHONY : graphics/src/gui/c2Text.i

# target to preprocess a source file
graphics/src/gui/c2Text.cpp.i:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/gui/c2Text.cpp.i
.PHONY : graphics/src/gui/c2Text.cpp.i

graphics/src/gui/c2Text.s: graphics/src/gui/c2Text.cpp.s

.PHONY : graphics/src/gui/c2Text.s

# target to generate assembly for a file
graphics/src/gui/c2Text.cpp.s:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/gui/c2Text.cpp.s
.PHONY : graphics/src/gui/c2Text.cpp.s

graphics/src/objects/c2Box_Graphics.o: graphics/src/objects/c2Box_Graphics.cpp.o

.PHONY : graphics/src/objects/c2Box_Graphics.o

# target to build an object file
graphics/src/objects/c2Box_Graphics.cpp.o:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/objects/c2Box_Graphics.cpp.o
.PHONY : graphics/src/objects/c2Box_Graphics.cpp.o

graphics/src/objects/c2Box_Graphics.i: graphics/src/objects/c2Box_Graphics.cpp.i

.PHONY : graphics/src/objects/c2Box_Graphics.i

# target to preprocess a source file
graphics/src/objects/c2Box_Graphics.cpp.i:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/objects/c2Box_Graphics.cpp.i
.PHONY : graphics/src/objects/c2Box_Graphics.cpp.i

graphics/src/objects/c2Box_Graphics.s: graphics/src/objects/c2Box_Graphics.cpp.s

.PHONY : graphics/src/objects/c2Box_Graphics.s

# target to generate assembly for a file
graphics/src/objects/c2Box_Graphics.cpp.s:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/objects/c2Box_Graphics.cpp.s
.PHONY : graphics/src/objects/c2Box_Graphics.cpp.s

graphics/src/objects/c2Cell_Graphics.o: graphics/src/objects/c2Cell_Graphics.cpp.o

.PHONY : graphics/src/objects/c2Cell_Graphics.o

# target to build an object file
graphics/src/objects/c2Cell_Graphics.cpp.o:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/objects/c2Cell_Graphics.cpp.o
.PHONY : graphics/src/objects/c2Cell_Graphics.cpp.o

graphics/src/objects/c2Cell_Graphics.i: graphics/src/objects/c2Cell_Graphics.cpp.i

.PHONY : graphics/src/objects/c2Cell_Graphics.i

# target to preprocess a source file
graphics/src/objects/c2Cell_Graphics.cpp.i:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/objects/c2Cell_Graphics.cpp.i
.PHONY : graphics/src/objects/c2Cell_Graphics.cpp.i

graphics/src/objects/c2Cell_Graphics.s: graphics/src/objects/c2Cell_Graphics.cpp.s

.PHONY : graphics/src/objects/c2Cell_Graphics.s

# target to generate assembly for a file
graphics/src/objects/c2Cell_Graphics.cpp.s:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/objects/c2Cell_Graphics.cpp.s
.PHONY : graphics/src/objects/c2Cell_Graphics.cpp.s

graphics/src/objects/c2Grid_Graphics.o: graphics/src/objects/c2Grid_Graphics.cpp.o

.PHONY : graphics/src/objects/c2Grid_Graphics.o

# target to build an object file
graphics/src/objects/c2Grid_Graphics.cpp.o:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/objects/c2Grid_Graphics.cpp.o
.PHONY : graphics/src/objects/c2Grid_Graphics.cpp.o

graphics/src/objects/c2Grid_Graphics.i: graphics/src/objects/c2Grid_Graphics.cpp.i

.PHONY : graphics/src/objects/c2Grid_Graphics.i

# target to preprocess a source file
graphics/src/objects/c2Grid_Graphics.cpp.i:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/objects/c2Grid_Graphics.cpp.i
.PHONY : graphics/src/objects/c2Grid_Graphics.cpp.i

graphics/src/objects/c2Grid_Graphics.s: graphics/src/objects/c2Grid_Graphics.cpp.s

.PHONY : graphics/src/objects/c2Grid_Graphics.s

# target to generate assembly for a file
graphics/src/objects/c2Grid_Graphics.cpp.s:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/objects/c2Grid_Graphics.cpp.s
.PHONY : graphics/src/objects/c2Grid_Graphics.cpp.s

graphics/src/objects/c2World_Graphics.o: graphics/src/objects/c2World_Graphics.cpp.o

.PHONY : graphics/src/objects/c2World_Graphics.o

# target to build an object file
graphics/src/objects/c2World_Graphics.cpp.o:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/objects/c2World_Graphics.cpp.o
.PHONY : graphics/src/objects/c2World_Graphics.cpp.o

graphics/src/objects/c2World_Graphics.i: graphics/src/objects/c2World_Graphics.cpp.i

.PHONY : graphics/src/objects/c2World_Graphics.i

# target to preprocess a source file
graphics/src/objects/c2World_Graphics.cpp.i:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/objects/c2World_Graphics.cpp.i
.PHONY : graphics/src/objects/c2World_Graphics.cpp.i

graphics/src/objects/c2World_Graphics.s: graphics/src/objects/c2World_Graphics.cpp.s

.PHONY : graphics/src/objects/c2World_Graphics.s

# target to generate assembly for a file
graphics/src/objects/c2World_Graphics.cpp.s:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/graphics/src/objects/c2World_Graphics.cpp.s
.PHONY : graphics/src/objects/c2World_Graphics.cpp.s

src/c2Cell.o: src/c2Cell.cpp.o

.PHONY : src/c2Cell.o

# target to build an object file
src/c2Cell.cpp.o:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/src/c2Cell.cpp.o
.PHONY : src/c2Cell.cpp.o

src/c2Cell.i: src/c2Cell.cpp.i

.PHONY : src/c2Cell.i

# target to preprocess a source file
src/c2Cell.cpp.i:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/src/c2Cell.cpp.i
.PHONY : src/c2Cell.cpp.i

src/c2Cell.s: src/c2Cell.cpp.s

.PHONY : src/c2Cell.s

# target to generate assembly for a file
src/c2Cell.cpp.s:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/src/c2Cell.cpp.s
.PHONY : src/c2Cell.cpp.s

src/c2Collisions.o: src/c2Collisions.cpp.o

.PHONY : src/c2Collisions.o

# target to build an object file
src/c2Collisions.cpp.o:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/src/c2Collisions.cpp.o
.PHONY : src/c2Collisions.cpp.o

src/c2Collisions.i: src/c2Collisions.cpp.i

.PHONY : src/c2Collisions.i

# target to preprocess a source file
src/c2Collisions.cpp.i:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/src/c2Collisions.cpp.i
.PHONY : src/c2Collisions.cpp.i

src/c2Collisions.s: src/c2Collisions.cpp.s

.PHONY : src/c2Collisions.s

# target to generate assembly for a file
src/c2Collisions.cpp.s:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/src/c2Collisions.cpp.s
.PHONY : src/c2Collisions.cpp.s

src/c2World.o: src/c2World.cpp.o

.PHONY : src/c2World.o

# target to build an object file
src/c2World.cpp.o:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/src/c2World.cpp.o
.PHONY : src/c2World.cpp.o

src/c2World.i: src/c2World.cpp.i

.PHONY : src/c2World.i

# target to preprocess a source file
src/c2World.cpp.i:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/src/c2World.cpp.i
.PHONY : src/c2World.cpp.i

src/c2World.s: src/c2World.cpp.s

.PHONY : src/c2World.s

# target to generate assembly for a file
src/c2World.cpp.s:
	$(MAKE) -f CMakeFiles/cells.elf.dir/build.make CMakeFiles/cells.elf.dir/src/c2World.cpp.s
.PHONY : src/c2World.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... cells.elf"
	@echo "... graphics/src/c2Functions.o"
	@echo "... graphics/src/c2Functions.i"
	@echo "... graphics/src/c2Functions.s"
	@echo "... graphics/src/c2Graphics.o"
	@echo "... graphics/src/c2Graphics.i"
	@echo "... graphics/src/c2Graphics.s"
	@echo "... graphics/src/c2Shader.o"
	@echo "... graphics/src/c2Shader.i"
	@echo "... graphics/src/c2Shader.s"
	@echo "... graphics/src/example.o"
	@echo "... graphics/src/example.i"
	@echo "... graphics/src/example.s"
	@echo "... graphics/src/glad.o"
	@echo "... graphics/src/glad.i"
	@echo "... graphics/src/glad.s"
	@echo "... graphics/src/gui/c2GUI.o"
	@echo "... graphics/src/gui/c2GUI.i"
	@echo "... graphics/src/gui/c2GUI.s"
	@echo "... graphics/src/gui/c2Text.o"
	@echo "... graphics/src/gui/c2Text.i"
	@echo "... graphics/src/gui/c2Text.s"
	@echo "... graphics/src/objects/c2Box_Graphics.o"
	@echo "... graphics/src/objects/c2Box_Graphics.i"
	@echo "... graphics/src/objects/c2Box_Graphics.s"
	@echo "... graphics/src/objects/c2Cell_Graphics.o"
	@echo "... graphics/src/objects/c2Cell_Graphics.i"
	@echo "... graphics/src/objects/c2Cell_Graphics.s"
	@echo "... graphics/src/objects/c2Grid_Graphics.o"
	@echo "... graphics/src/objects/c2Grid_Graphics.i"
	@echo "... graphics/src/objects/c2Grid_Graphics.s"
	@echo "... graphics/src/objects/c2World_Graphics.o"
	@echo "... graphics/src/objects/c2World_Graphics.i"
	@echo "... graphics/src/objects/c2World_Graphics.s"
	@echo "... src/c2Cell.o"
	@echo "... src/c2Cell.i"
	@echo "... src/c2Cell.s"
	@echo "... src/c2Collisions.o"
	@echo "... src/c2Collisions.i"
	@echo "... src/c2Collisions.s"
	@echo "... src/c2World.o"
	@echo "... src/c2World.i"
	@echo "... src/c2World.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

